// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/colection/service/v1/colection.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateColectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	TargetId int64 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
}

func (x *CreateColectionRequest) Reset() {
	*x = CreateColectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_colection_service_v1_colection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateColectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColectionRequest) ProtoMessage() {}

func (x *CreateColectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_colection_service_v1_colection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColectionRequest.ProtoReflect.Descriptor instead.
func (*CreateColectionRequest) Descriptor() ([]byte, []int) {
	return file_api_colection_service_v1_colection_proto_rawDescGZIP(), []int{0}
}

func (x *CreateColectionRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateColectionRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CreateColectionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateColectionReply) Reset() {
	*x = CreateColectionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_colection_service_v1_colection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateColectionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColectionReply) ProtoMessage() {}

func (x *CreateColectionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_colection_service_v1_colection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColectionReply.ProtoReflect.Descriptor instead.
func (*CreateColectionReply) Descriptor() ([]byte, []int) {
	return file_api_colection_service_v1_colection_proto_rawDescGZIP(), []int{1}
}

type ListColectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Type  int64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ListColectionRequest) Reset() {
	*x = ListColectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_colection_service_v1_colection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListColectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColectionRequest) ProtoMessage() {}

func (x *ListColectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_colection_service_v1_colection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColectionRequest.ProtoReflect.Descriptor instead.
func (*ListColectionRequest) Descriptor() ([]byte, []int) {
	return file_api_colection_service_v1_colection_proto_rawDescGZIP(), []int{2}
}

func (x *ListColectionRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListColectionRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListColectionRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ListColectionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ListColectionReply_Data `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListColectionReply) Reset() {
	*x = ListColectionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_colection_service_v1_colection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListColectionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColectionReply) ProtoMessage() {}

func (x *ListColectionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_colection_service_v1_colection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColectionReply.ProtoReflect.Descriptor instead.
func (*ListColectionReply) Descriptor() ([]byte, []int) {
	return file_api_colection_service_v1_colection_proto_rawDescGZIP(), []int{3}
}

func (x *ListColectionReply) GetList() []*ListColectionReply_Data {
	if x != nil {
		return x.List
	}
	return nil
}

type ListColectionReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Banner string `protobuf:"bytes,3,opt,name=banner,proto3" json:"banner,omitempty"`
}

func (x *ListColectionReply_Data) Reset() {
	*x = ListColectionReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_colection_service_v1_colection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListColectionReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColectionReply_Data) ProtoMessage() {}

func (x *ListColectionReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_colection_service_v1_colection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColectionReply_Data.ProtoReflect.Descriptor instead.
func (*ListColectionReply_Data) Descriptor() ([]byte, []int) {
	return file_api_colection_service_v1_colection_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListColectionReply_Data) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListColectionReply_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListColectionReply_Data) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

var File_api_colection_service_v1_colection_proto protoreflect.FileDescriptor

var file_api_colection_service_v1_colection_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0x49, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22,
	0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x54, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x9f, 0x01,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x42, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x32,
	0xef, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x73, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x6d, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x23, 0x5a, 0x21, 0x63, 0x61, 0x73, 0x73, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x6f, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_colection_service_v1_colection_proto_rawDescOnce sync.Once
	file_api_colection_service_v1_colection_proto_rawDescData = file_api_colection_service_v1_colection_proto_rawDesc
)

func file_api_colection_service_v1_colection_proto_rawDescGZIP() []byte {
	file_api_colection_service_v1_colection_proto_rawDescOnce.Do(func() {
		file_api_colection_service_v1_colection_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_colection_service_v1_colection_proto_rawDescData)
	})
	return file_api_colection_service_v1_colection_proto_rawDescData
}

var file_api_colection_service_v1_colection_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_colection_service_v1_colection_proto_goTypes = []interface{}{
	(*CreateColectionRequest)(nil),  // 0: api.colection.service.v1.CreateColectionRequest
	(*CreateColectionReply)(nil),    // 1: api.colection.service.v1.CreateColectionReply
	(*ListColectionRequest)(nil),    // 2: api.colection.service.v1.ListColectionRequest
	(*ListColectionReply)(nil),      // 3: api.colection.service.v1.ListColectionReply
	(*ListColectionReply_Data)(nil), // 4: api.colection.service.v1.ListColectionReply.Data
}
var file_api_colection_service_v1_colection_proto_depIdxs = []int32{
	4, // 0: api.colection.service.v1.ListColectionReply.list:type_name -> api.colection.service.v1.ListColectionReply.Data
	0, // 1: api.colection.service.v1.Colection.CreateColection:input_type -> api.colection.service.v1.CreateColectionRequest
	2, // 2: api.colection.service.v1.Colection.ListColection:input_type -> api.colection.service.v1.ListColectionRequest
	1, // 3: api.colection.service.v1.Colection.CreateColection:output_type -> api.colection.service.v1.CreateColectionReply
	3, // 4: api.colection.service.v1.Colection.ListColection:output_type -> api.colection.service.v1.ListColectionReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_colection_service_v1_colection_proto_init() }
func file_api_colection_service_v1_colection_proto_init() {
	if File_api_colection_service_v1_colection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_colection_service_v1_colection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateColectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_colection_service_v1_colection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateColectionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_colection_service_v1_colection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListColectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_colection_service_v1_colection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListColectionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_colection_service_v1_colection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListColectionReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_colection_service_v1_colection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_colection_service_v1_colection_proto_goTypes,
		DependencyIndexes: file_api_colection_service_v1_colection_proto_depIdxs,
		MessageInfos:      file_api_colection_service_v1_colection_proto_msgTypes,
	}.Build()
	File_api_colection_service_v1_colection_proto = out.File
	file_api_colection_service_v1_colection_proto_rawDesc = nil
	file_api_colection_service_v1_colection_proto_goTypes = nil
	file_api_colection_service_v1_colection_proto_depIdxs = nil
}
