// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ShopAdminHTTPServer interface {
	CreateShopAdmin(context.Context, *CreateShopAdminRequest) (*CreateShopAdminReply, error)
}

func RegisterShopAdminHTTPServer(s *http.Server, srv ShopAdminHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v/shop", _ShopAdmin_CreateShopAdmin0_HTTP_Handler(srv))
}

func _ShopAdmin_CreateShopAdmin0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShopAdminRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.shop.v1.Shop_admin/CreateShopAdmin")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShopAdmin(ctx, req.(*CreateShopAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShopAdminReply)
		return ctx.Result(200, reply)
	}
}

type ShopAdminHTTPClient interface {
	CreateShopAdmin(ctx context.Context, req *CreateShopAdminRequest, opts ...http.CallOption) (rsp *CreateShopAdminReply, err error)
}

type ShopAdminHTTPClientImpl struct {
	cc *http.Client
}

func NewShopAdminHTTPClient(client *http.Client) ShopAdminHTTPClient {
	return &ShopAdminHTTPClientImpl{client}
}

func (c *ShopAdminHTTPClientImpl) CreateShopAdmin(ctx context.Context, in *CreateShopAdminRequest, opts ...http.CallOption) (*CreateShopAdminReply, error) {
	var out CreateShopAdminReply
	pattern := "/admin/v/shop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.shop.v1.Shop_admin/CreateShopAdmin"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
