// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ShopAdminHTTPServer interface {
	ListShopAdmin(context.Context, *ListShopAdminRequest) (*ListShopAdminReply, error)
}

func RegisterShopAdminHTTPServer(s *http.Server, srv ShopAdminHTTPServer) {
	r := s.Route("/")
	r.GET("/admin/v1/shop/list", _ShopAdmin_ListShopAdmin0_HTTP_Handler(srv))
}

func _ShopAdmin_ListShopAdmin0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListShopAdminRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.shop.v1.Shop_admin/ListShopAdmin")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShopAdmin(ctx, req.(*ListShopAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShopAdminReply)
		return ctx.Result(200, reply)
	}
}

type ShopAdminHTTPClient interface {
	ListShopAdmin(ctx context.Context, req *ListShopAdminRequest, opts ...http.CallOption) (rsp *ListShopAdminReply, err error)
}

type ShopAdminHTTPClientImpl struct {
	cc *http.Client
}

func NewShopAdminHTTPClient(client *http.Client) ShopAdminHTTPClient {
	return &ShopAdminHTTPClientImpl{client}
}

func (c *ShopAdminHTTPClientImpl) ListShopAdmin(ctx context.Context, in *ListShopAdminRequest, opts ...http.CallOption) (*ListShopAdminReply, error) {
	var out ListShopAdminReply
	pattern := "/admin/v1/shop/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.shop.v1.Shop_admin/ListShopAdmin"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
