// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/shopcar/service/v1/shopcar.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShopcarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId int64 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *CreateShopcarRequest) Reset() {
	*x = CreateShopcarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShopcarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopcarRequest) ProtoMessage() {}

func (x *CreateShopcarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopcarRequest.ProtoReflect.Descriptor instead.
func (*CreateShopcarRequest) Descriptor() ([]byte, []int) {
	return file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShopcarRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type CreateShopcarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateShopcarReply) Reset() {
	*x = CreateShopcarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShopcarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopcarReply) ProtoMessage() {}

func (x *CreateShopcarReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopcarReply.ProtoReflect.Descriptor instead.
func (*CreateShopcarReply) Descriptor() ([]byte, []int) {
	return file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP(), []int{1}
}

type DeleteShopcarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopCarId int64 `protobuf:"varint,1,opt,name=shop_car_id,json=shopCarId,proto3" json:"shop_car_id,omitempty"`
}

func (x *DeleteShopcarRequest) Reset() {
	*x = DeleteShopcarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShopcarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopcarRequest) ProtoMessage() {}

func (x *DeleteShopcarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopcarRequest.ProtoReflect.Descriptor instead.
func (*DeleteShopcarRequest) Descriptor() ([]byte, []int) {
	return file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteShopcarRequest) GetShopCarId() int64 {
	if x != nil {
		return x.ShopCarId
	}
	return 0
}

type DeleteShopcarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShopcarReply) Reset() {
	*x = DeleteShopcarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShopcarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopcarReply) ProtoMessage() {}

func (x *DeleteShopcarReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopcarReply.ProtoReflect.Descriptor instead.
func (*DeleteShopcarReply) Descriptor() ([]byte, []int) {
	return file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP(), []int{3}
}

type ListShopcarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListShopcarRequest) Reset() {
	*x = ListShopcarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShopcarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopcarRequest) ProtoMessage() {}

func (x *ListShopcarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopcarRequest.ProtoReflect.Descriptor instead.
func (*ListShopcarRequest) Descriptor() ([]byte, []int) {
	return file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP(), []int{4}
}

func (x *ListShopcarRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShopcarRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListShopcarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ListShopcarReply_ShopCarList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListShopcarReply) Reset() {
	*x = ListShopcarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShopcarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopcarReply) ProtoMessage() {}

func (x *ListShopcarReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopcarReply.ProtoReflect.Descriptor instead.
func (*ListShopcarReply) Descriptor() ([]byte, []int) {
	return file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP(), []int{5}
}

func (x *ListShopcarReply) GetList() []*ListShopcarReply_ShopCarList {
	if x != nil {
		return x.List
	}
	return nil
}

type ListShopcarReply_ShopCarList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName   string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductBanner string `protobuf:"bytes,3,opt,name=product_banner,json=productBanner,proto3" json:"product_banner,omitempty"`
}

func (x *ListShopcarReply_ShopCarList) Reset() {
	*x = ListShopcarReply_ShopCarList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShopcarReply_ShopCarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopcarReply_ShopCarList) ProtoMessage() {}

func (x *ListShopcarReply_ShopCarList) ProtoReflect() protoreflect.Message {
	mi := &file_api_shopcar_service_v1_shopcar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopcarReply_ShopCarList.ProtoReflect.Descriptor instead.
func (*ListShopcarReply_ShopCarList) Descriptor() ([]byte, []int) {
	return file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListShopcarReply_ShopCarList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListShopcarReply_ShopCarList) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ListShopcarReply_ShopCarList) GetProductBanner() string {
	if x != nil {
		return x.ProductBanner
	}
	return ""
}

var File_api_shopcar_service_v1_shopcar_proto protoreflect.FileDescriptor

var file_api_shopcar_service_v1_shopcar_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70,
	0x63, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x35,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x36, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x63, 0x61, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x43, 0x61,
	0x72, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x70, 0x63, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3e, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x67, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x32, 0xc4, 0x02, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x12, 0x69, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x12, 0x2c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68,
	0x6f, 0x70, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70,
	0x63, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x69, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x63, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x63,
	0x61, 0x72, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70,
	0x63, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x21, 0x5a, 0x1f, 0x63, 0x61, 0x73, 0x73,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_shopcar_service_v1_shopcar_proto_rawDescOnce sync.Once
	file_api_shopcar_service_v1_shopcar_proto_rawDescData = file_api_shopcar_service_v1_shopcar_proto_rawDesc
)

func file_api_shopcar_service_v1_shopcar_proto_rawDescGZIP() []byte {
	file_api_shopcar_service_v1_shopcar_proto_rawDescOnce.Do(func() {
		file_api_shopcar_service_v1_shopcar_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_shopcar_service_v1_shopcar_proto_rawDescData)
	})
	return file_api_shopcar_service_v1_shopcar_proto_rawDescData
}

var file_api_shopcar_service_v1_shopcar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_shopcar_service_v1_shopcar_proto_goTypes = []interface{}{
	(*CreateShopcarRequest)(nil),         // 0: api.shopcar.service.v1.CreateShopcarRequest
	(*CreateShopcarReply)(nil),           // 1: api.shopcar.service.v1.CreateShopcarReply
	(*DeleteShopcarRequest)(nil),         // 2: api.shopcar.service.v1.DeleteShopcarRequest
	(*DeleteShopcarReply)(nil),           // 3: api.shopcar.service.v1.DeleteShopcarReply
	(*ListShopcarRequest)(nil),           // 4: api.shopcar.service.v1.ListShopcarRequest
	(*ListShopcarReply)(nil),             // 5: api.shopcar.service.v1.ListShopcarReply
	(*ListShopcarReply_ShopCarList)(nil), // 6: api.shopcar.service.v1.ListShopcarReply.ShopCarList
}
var file_api_shopcar_service_v1_shopcar_proto_depIdxs = []int32{
	6, // 0: api.shopcar.service.v1.ListShopcarReply.list:type_name -> api.shopcar.service.v1.ListShopcarReply.ShopCarList
	0, // 1: api.shopcar.service.v1.Shopcar.CreateShopcar:input_type -> api.shopcar.service.v1.CreateShopcarRequest
	2, // 2: api.shopcar.service.v1.Shopcar.DeleteShopcar:input_type -> api.shopcar.service.v1.DeleteShopcarRequest
	4, // 3: api.shopcar.service.v1.Shopcar.ListShopcar:input_type -> api.shopcar.service.v1.ListShopcarRequest
	1, // 4: api.shopcar.service.v1.Shopcar.CreateShopcar:output_type -> api.shopcar.service.v1.CreateShopcarReply
	3, // 5: api.shopcar.service.v1.Shopcar.DeleteShopcar:output_type -> api.shopcar.service.v1.DeleteShopcarReply
	5, // 6: api.shopcar.service.v1.Shopcar.ListShopcar:output_type -> api.shopcar.service.v1.ListShopcarReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_shopcar_service_v1_shopcar_proto_init() }
func file_api_shopcar_service_v1_shopcar_proto_init() {
	if File_api_shopcar_service_v1_shopcar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_shopcar_service_v1_shopcar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShopcarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shopcar_service_v1_shopcar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShopcarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shopcar_service_v1_shopcar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShopcarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shopcar_service_v1_shopcar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShopcarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shopcar_service_v1_shopcar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShopcarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shopcar_service_v1_shopcar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShopcarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shopcar_service_v1_shopcar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShopcarReply_ShopCarList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_shopcar_service_v1_shopcar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shopcar_service_v1_shopcar_proto_goTypes,
		DependencyIndexes: file_api_shopcar_service_v1_shopcar_proto_depIdxs,
		MessageInfos:      file_api_shopcar_service_v1_shopcar_proto_msgTypes,
	}.Build()
	File_api_shopcar_service_v1_shopcar_proto = out.File
	file_api_shopcar_service_v1_shopcar_proto_rawDesc = nil
	file_api_shopcar_service_v1_shopcar_proto_goTypes = nil
	file_api_shopcar_service_v1_shopcar_proto_depIdxs = nil
}
