// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type WsHTTPServer interface {
	Chat(context.Context, *ChatRequest) (*ChatReply, error)
}

func RegisterWsHTTPServer(s *http.Server, srv WsHTTPServer) {
	r := s.Route("/")
	r.GET("/admin/v1/shop/list", _Ws_Chat0_HTTP_Handler(srv))
}

func _Ws_Chat0_HTTP_Handler(srv WsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.ws.service.v1.Ws/Chat")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Chat(ctx, req.(*ChatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatReply)
		return ctx.Result(200, reply)
	}
}

type WsHTTPClient interface {
	Chat(ctx context.Context, req *ChatRequest, opts ...http.CallOption) (rsp *ChatReply, err error)
}

type WsHTTPClientImpl struct {
	cc *http.Client
}

func NewWsHTTPClient(client *http.Client) WsHTTPClient {
	return &WsHTTPClientImpl{client}
}

func (c *WsHTTPClientImpl) Chat(ctx context.Context, in *ChatRequest, opts ...http.CallOption) (*ChatReply, error) {
	var out ChatReply
	pattern := "/admin/v1/shop/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.ws.service.v1.Ws/Chat"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
